# Introduction to NumPy

# Why Use NumPy?

# Installing NumPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Creating Arrays

In [3]:
# From a Python list
# Creating a 1D Array (Matrix)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [5]:
# Creating a 2D Array (Matrix)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
# Creating Arrays with Functions

zeros_arr = np.zeros((2, 3))  # 2x3 array of zeros
ones_arr = np.ones((3, 3))    # 3x3 array of ones
range_arr = np.arange(0, 10, 2)  # Array from 0 to 10 with a step of 2
linspace_arr = np.linspace(0, 1, 5)  # 5 evenly spaced numbers between 0 and 1

print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(range_arr)

[0 2 4 6 8]


In [10]:
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [33]:
zeros = np.zeros((3, 3))                # 3x3 zeros matrix
ones = np.ones((2, 4))                  # 2x4 ones matrix
identity = np.eye(3)                    # Identity matrix
range_arr = np.arange(0, 10, 2)         # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)         # [0.0, 0.25, 0.5, 0.75, 1.0]
random_arr = np.random.rand(2, 3)       # Random values (0-1)

In [37]:
print(zeros)
print(ones)
print(identity)
print(range_arr)
print(linspace)
print(random_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.83842668 0.66212521 0.60273117]
 [0.29782077 0.9892547  0.13185223]]


# Array Attributes

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # (2, 3) → 2 rows, 3 columns
print(arr.ndim)    # 2 → dimensions
print(arr.size)    # 6 → total elements
print(arr.dtype)   # int64 → data type

(2, 3)
2
6
int32


# Array Operations

In [12]:
# Indexing & Slicing

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])       # 10 (first element)
print(arr[1:4])     # [20 30 40] (slicing) # # Slicing elements from index 1 to 3

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[1, 2])  # 6 (row 1, column 2)
print(matrix[:, 1])  # [2 5] (all rows, column 1)

10
[20 30 40]
6
[2 5]


In [13]:
# Reshaping Arrays

arr = np.arange(1, 10)  # [1 2 3 4 5 6 7 8 9]
reshaped = arr.reshape(3, 3)
print(reshaped)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
arr = np.arange(1, 10)  # [1, 2, 3, 4, 5, 6, 7, 8, 9]
reshaped = arr.reshape(3, 3)  # 3x3 matrix
flattened = reshaped.flatten() # Back to 1D

In [40]:
print(reshaped)
print(flattened)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [16]:
# Mathematical Operations

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9] (element-wise addition)
print(a * b)   # [4 10 18] (element-wise multiplication)
print(a - b)   
print(a / b)   
print(np.dot(a, b))  # 32 (dot product)

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]
32


In [17]:
# Mathematical Operations

arr = np.array([1, 2, 3, 4, 5])

# Square root of each element
print(np.sqrt(arr))

# Exponential of each element
print(np.exp(arr))

# Natural logarithm
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [15]:
# Aggregate Functions

arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))    # 15
print(np.mean(arr))   # 3.0
print(np.max(arr))    # 5
print(np.min(arr))    # 1
print(np.std(arr))    # 1.414 (standard deviation)

15
3.0
5
1
1.4142135623730951


# Linear Algebra with NumPy

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
print(np.matmul(A, B))

[[19 22]
 [43 50]]


In [19]:
# Transpose

print(A.T)

[[1 3]
 [2 4]]


In [20]:
# Inverse

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Random Number Generation

In [21]:
# Generate a random integer between 0 and 10
random_int = np.random.randint(0, 10)

# Generate an array of random numbers from a normal distribution
random_arr = np.random.randn(5)

print(random_int)
print(random_arr)


5
[-0.36601219 -1.39907743  1.10204523 -0.05953987 -1.58919952]


# Concatenating Arrays

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate two 1D arrays
concatenated_arr = np.concatenate([arr1, arr2])
print(concatenated_arr)


[1 2 3 4 5 6]


# Stacking Arrays

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays vertically
stacked_arr = np.vstack([arr1, arr2])
print(stacked_arr)


[[1 2 3]
 [4 5 6]]


# Handling Missing Data

In [25]:
# NumPy uses np.nan for missing values.

arr = np.array([1, 2, np.nan, 4])
print(np.isnan(arr))  # [False False  True False]


[False False  True False]


In [26]:
# Removing NaN values
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)

[1. 2. 4.]


# Saving & Loading Arrays

In [27]:
# Save to file
np.save('my_array.npy', arr)

# Load from file
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[ 1.  2. nan  4.]


# Real-World Data Analytics Example

In [28]:
# A dataset of exam scores
scores = np.array([85, 90, 78, 92, 88, 76, 95, 89])

# Calculate the mean and standard deviation
mean_score = np.mean(scores)
std_dev_score = np.std(scores)

print(f"Mean score: {mean_score}")
print(f"Standard Deviation: {std_dev_score}")


Mean score: 86.625
Standard Deviation: 6.203577596838779


In [30]:
# Sample sales data (3 products, 5 days)
sales = np.array([
    [100, 150, 200, 180, 220],  # Product 1
    [80, 90, 110, 95, 120],     # Product 2
    [50, 60, 70, 65, 75]        # Product 3
])

# Total sales per product
total_sales = np.sum(sales, axis=1)
print("Total sales per product:", total_sales)

Total sales per product: [850 495 320]


In [31]:
# Average daily sales
avg_daily = np.mean(sales, axis=0)
print("Average daily sales:", avg_daily)

Average daily sales: [ 76.66666667 100.         126.66666667 113.33333333 138.33333333]


In [32]:
# Best-selling day
best_day = np.argmax(np.sum(sales, axis=0))
print("Best-selling day:", best_day)

Best-selling day: 4


# What's Next? 